version: 2
jobs:
  test:
    working_directory: /go/src/github.com/davilag/crawler
    steps:
      - checkout
      - run:
          name: Get dependencies
          command: go get -t -d -v ./...
      - run:
          name: Run tests & benchmarks
          command: go test -v ./... -bench=.
workflows:
  version: 2
  validate:
    jobs:
      - test